strategy_engine:
  enabled_strategies:
  - QuantumEdge
  - PCRReversal
  - GammaScalping
  - InstitutionalFootprint
  - VolatilityHarvesting
  - VolatilityCapture
  - MomentumImpulse
  - VWAPDeviation
  - MarketProfileGapFill
  execution_parameters:
    confidence_threshold: 0.75
    max_daily_trades: 50
    max_positions: 5
    min_signal_strength: 75
  optimization_features:
    confidence_boosting: true
    dynamic_sizing: true
    regime_adjustment: true
    volatility_capture: true
